name: Health Check

on:
  schedule:
    - cron: '46 * * * *' 

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://fso-cicd-pokedex.herokuapp.com/
          max-attempts: 3
          retry-delay: 3s
      - name: Healthcheck success notification
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          username: ${{ github.actor }}
          details: Healthcheck passed
          footer: ${{ github.repository }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Healthcheck failure notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          username: ${{ github.actor }}
          details: Healtcheck failed
          footer: ${{ github.repository }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}